baseURL: http://example.org
languageCode: en-gb
title: Snippets

theme:
  - docdock
  - utils

params:
  enableGitInfo: true
  disableNavChevron: true

outputs:
  home:
    - HTML
    - RSS
    - JSON


enableRobotsTXT: true
enableEmoji: true
stepAnalysis: true

pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
pygmentsUseClasses: true

blackfriday:
  smartypants: false
