baseURL: https://snippets.theorangeone.net
languageCode: en-gb
title: Snippets

theme:
  - docdock
  - utils

params:
  enableGitInfo: true
  disableNavChevron: true

outputs:
  home:
    - HTML
    - RSS
    - JSON


enableRobotsTXT: true
enableEmoji: true
stepAnalysis: true

pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
pygmentsUseClasses: true

blackfriday:
  smartypants: false

disableKinds:
  - taxonomy
  - taxonomyTerm

assetDir: .

menu:
  shortcuts:
    - name: <i class='fa fa-globe'></i> <label>Website</label>
      url: https://theorangeone.net
    - name: <i class='fa fa-github'></i> <label>GitHub</label>
      url: https://github.com/RealOrangeOne/snippets
